"""empty message

Revision ID: 245edf974fa4
Revises: 29e84977af6f
Create Date: 2024-02-14 10:54:10.028978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '245edf974fa4'
down_revision = '29e84977af6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_trening', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trener_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'trener', ['trener_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_trening', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('trener_id')

    # ### end Alembic commands ###
