"""empty message

Revision ID: 2f6bbce5b96e
Revises: 5fe2fcc9c2f9
Create Date: 2024-02-12 19:34:09.982207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f6bbce5b96e'
down_revision = '5fe2fcc9c2f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_trening', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trener_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'trener', ['trener_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_trening', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('trener_id')

    # ### end Alembic commands ###
