"""empty message

Revision ID: 48095fc6387c
Revises: fe7356182aff
Create Date: 2024-01-31 13:28:25.504746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48095fc6387c'
down_revision = 'fe7356182aff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('surname', sa.String(length=150), nullable=True),
    sa.Column('hashed_password', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=45), nullable=True),
    sa.Column('telephone', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
