"""empty message

Revision ID: 5fe2fcc9c2f9
Revises: 48095fc6387c
Create Date: 2024-02-03 18:46:49.702445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fe2fcc9c2f9'
down_revision = '48095fc6387c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trener', sa.Column('url_image', sa.String(length=250), nullable=True))
    op.add_column('trener', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trener', 'description')
    op.drop_column('trener', 'url_image')
    # ### end Alembic commands ###
