"""empty message

Revision ID: a5f7287907db
Revises: 
Create Date: 2024-01-25 15:14:48.596623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5f7287907db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_trening',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trening', sa.String(length=150), nullable=True),
    sa.Column('trener', sa.String(length=100), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('trening')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trening',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tipe', sa.VARCHAR(length=200), nullable=True),
    sa.Column('day', sa.VARCHAR(), nullable=True),
    sa.Column('time', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('group_trening')
    # ### end Alembic commands ###
