"""empty message

Revision ID: d3a7ebd92ac8
Revises: 245edf974fa4
Create Date: 2024-02-14 11:20:31.688185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3a7ebd92ac8'
down_revision = '245edf974fa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_trening', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trener_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fkpersonal_treningtrener_idtrener'), 'trener', ['trener_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_trening', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fkpersonal_treningtrener_idtrener'), type_='foreignkey')
        batch_op.drop_column('trener_id')

    # ### end Alembic commands ###
