"""empty message

Revision ID: e7e2954003c4
Revises: d3a7ebd92ac8
Create Date: 2024-02-20 18:28:38.872864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7e2954003c4'
down_revision = 'd3a7ebd92ac8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_trening2trener',
    sa.Column('group_trning_id', sa.Integer(), nullable=True),
    sa.Column('trener_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_trning_id'], ['group_trening.id'], name=op.f('fkgroup_trening2trenergroup_trning_idgroup_trening')),
    sa.ForeignKeyConstraint(['trener_id'], ['trener.id'], name=op.f('fkgroup_trening2trenertrener_idtrener'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_trening2trener')
    # ### end Alembic commands ###
