"""empty message

Revision ID: fe7356182aff
Revises: 2cd8dfd5ba20
Create Date: 2024-01-29 16:20:10.610088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe7356182aff'
down_revision = '2cd8dfd5ba20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_trening', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('update_at')

    with op.batch_alter_table('personal_trening', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('update_at')

    with op.batch_alter_table('trener', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('update_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trener', schema=None) as batch_op:
        batch_op.add_column(sa.Column('update_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('personal_trening', schema=None) as batch_op:
        batch_op.add_column(sa.Column('update_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('group_trening', schema=None) as batch_op:
        batch_op.add_column(sa.Column('update_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
